### ISSUE TITLE
Can't access to pages of sample app after login in WSO2

### ISSUE THREAD

**Issue by SMakhrov** [wso2-extensions/identity-samples-spring-boot#5]
Hi!

I have tried this sample app, but after login in WSO2 it returning me to this page: http://localhost/login?error
What is wrong? Please help.
my application.yaml:
```
server:
  port: 80

logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE

provider:
  host: https://localhost:9443 #Change the host

client:
  client-id: C9szMcMGvX8HO9l7yFDnf70bv08a
  client-secret: TiVLEvQzSNfHoezGQp5DIzWOnHIa
  post-logout-uri: http://localhost/login
  scope: openid
  authorization-grant-type: authorization_code


#No need to change the following configurations
spring:
  security:
    oauth2:
      client:
        registration:
          wso2:
            client-name : WSO2 Identity Server
            client-id: ${client.client-id} #Change client-id
            client-secret: ${client.client-secret} # Change client-secret
            authorization-grant-type: ${client.authorization-grant-type}
            redirect-uri: "{baseUrl}/login/oauth2/code/wso2"
            scope: ${client.scope}
        provider:
          wso2:
            authorization-uri: ${provider.host}/oauth2/authorize
            token-uri: ${provider.host}/oauth2/token
            user-info-uri: ${provider.host}/oauth2/userinfo
            jwk-set-uri: ${provider.host}/oauth2/jwks
  thymeleaf:
    cache: false

```

I have installed locally WSO2. It's available at https://localhost:9443
